{% set name = "cylc-uiserver" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f6d58085c9d8f3a6d4241343335371a9588cf667447a2c84b420eebee6bae5f5

build:
  number: 0
  noarch: python

requirements:
  host:
    - __unix
    - python >=3.7
    - pip
  run:
    - __unix
    - python >=3.7

outputs:
  # base package with only required dependencies
  # (e.g. for single-user setups)
  - name: {{ name }}-base
    build:
      script: python -m pip install . --no-deps --ignore-installed -vv
      noarch: python
    requirements:
      host:
        - __unix
        - python >=3.7
        - pip
      run:
        - __unix
        - python >=3.7
        - cylc-flow-base >=8.0,<8.1
        - tornado >=6.1
        - graphene-tornado >=2.6.0,<2.7
        - graphql-ws ==0.4.4
        - jupyter_server >=1.10.2,<2.0
        - traitlets >=5.0

        # Transitive dependencies that we directly (lightly) use:
        - pyzmq
        - graphene
        - graphql-core

        # Fix lack of upper pin for rx in graphql-core<2.3.0 (remove when
        # upgrading graphene to 3.0):
        - rx >=1.6,<2

    test:
      files:
        - tests/test_packaging.py
      imports:
        - cylc.flow
        - cylc.uiserver
      commands:
        - cylc version --long
        - cylc gui --help
        - command -v jupyter-cylc
        - ./tests/test_packaging.py ui
        - ./tests/test_packaging.py py.typed

  # UIS with the JupyterHub "base" package
  # (e.g. for sites that provide their own configurable HTTP proxy)
  - name: {{ name }}-hub-base
    build:
      script: python -m pip install .[hub] --no-deps --ignore-installed -vv
      noarch: python
    requirements:
      host:
        - __unix
        - python >=3.7
        - pip
      run:
        - {{ pin_subpackage(name + "-base", exact=True) }}
        - jupyterhub-base >=1.4.0
    test:
      files:
        - tests/test_packaging.py
      imports:
        - cylc.flow
        - cylc.uiserver
      commands:
        - cylc version --long
        - cylc gui --help
        - cylc hubapp --help
        - command -v jupyter-cylc
        - command -v jupyter-cylchubapp
        - ./tests/test_packaging.py ui
        - ./tests/test_packaging.py py.typed

  # UIS with the full JupyterHub package
  # (recommended)
  - name: {{ name }}
    build:
      script: python -m pip install .[hub] --no-deps --ignore-installed -vv
      noarch: python
    requirements:
      host:
        - __unix
        - python >=3.7
        - pip
      run:
        - {{ pin_subpackage(name + "-base", exact=True) }}
        - jupyterhub >=1.4.0
    test:
      files:
        - tests/test_packaging.py
      imports:
        - cylc.flow
        - cylc.uiserver
      commands:
        - cylc version --long
        - cylc gui --help
        - cylc hubapp --help
        - configurable-http-proxy --help
        - command -v jupyter-cylc
        - command -v jupyter-cylchubapp
        - ./tests/test_packaging.py ui
        - ./tests/test_packaging.py py.typed

about:
  home: https://github.com/cylc/cylc-uiserver
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: Cylc UI Server
  description: |
    This project contains the Cylc UI Server.
    A JupyterHub-compatible application, used to display
    the Cylc UI (or simply UI) to users, and to communicate
    with Workflow Services (WFS).
  doc_url: https://github.com/cylc/cylc-uiserver
  dev_url: https://github.com/cylc/cylc-uiserver

extra:
  recipe-maintainers:
    - hjoliver
    - oliver-sanders
    - MetRonnie
    - wxtim
