{% set name = "cylc-uiserver" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0e6678036d7d9dc419a598e58b453068f994e0fc19f0a89ab78fb12c89379094

build:
  number: 0
  # cylc-uiserver provides JupyterHub extensions and a small Jupyter Application. As JupyterHub
  # does not run on Windows, we skip the build for that platform here
  skip: true  # [py<37 or not linux]
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  # We use graphene and traitlets only lightly, so accepting the transitive
  # versions from graphene-tornado and jupyterhub.
  run:
    - python
    - cylc-flow ==8.0b0
    - jupyterhub >=1.3.0,<1.4
    - tornado >=6.1,<6.2
    - graphene-tornado >=2.6.0,<2.7
    - graphql-core <3,>=2.1
    - rx >=1.6,<2 # TODO: https://github.com/conda-forge/cylc-feedstock/pull/3#issuecomment-660716268
    - graphql-ws >=0.3.0,<0.4
    - traitlets
    - graphene

test:
  imports:
    - cylc.uiserver
  commands:
    - cylc uiserver --help

about:
  home: https://github.com/cylc/cylc-uiserver
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: Cylc UI Server

  description: |
    This project contains the Cylc UI Server.
    A JupyterHub-compatible application, used to display
    the Cylc UI (or simply UI) to users, and to communicate
    with Workflow Services (WFS).
  doc_url: https://github.com/cylc/cylc-uiserver
  dev_url: https://github.com/cylc/cylc-uiserver

extra:
  recipe-maintainers:
    - hjoliver
    - kinow
    - oliver-sanders
