{% set name = "cylc-uiserver" %}
{% set version = "1.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2f019ac1e6fb78bab612008bc0cc9f2852ce4056d79ef01c46846561b6e7a882

build:
  number: 0
  noarch: python

requirements:
  host:
    - __unix
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - __unix
    - python >={{ python_min }}

outputs:
  # base package with only required dependencies
  # (e.g. for single-user setups)
  - name: {{ name }}-base
    build:
      script: python -m pip install . --no-deps --ignore-installed -vv
      noarch: python
    requirements:
      host:
        - __unix
        - python {{ python_min }}
        - pip
        - setuptools
      run:
        - __unix
        - python >={{ python_min }}
        - cylc-flow-base >=8.6.2,<8.7
        - ansimarkup >=1
        - jupyter_server >=2.13
        - packaging
        - psutil
        - tornado >=6.5
        - traitlets >=5.2.1

        # Transitive dependencies that we directly (lightly) use:
        - pyzmq
        - graphene
        - requests

    test:
      requires:
        - python {{ python_min }}
      files:
        - tests/test_packaging.py
      imports:
        - cylc.flow
        - cylc.uiserver
      commands:
        - cylc version --long
        - cylc gui --help
        - command -v jupyter-cylc
        - ./tests/test_packaging.py ui
        - ./tests/test_packaging.py py.typed

  # UIS with the JupyterHub "base" package
  # (e.g. for sites that provide their own configurable HTTP proxy)
  - name: {{ name }}-hub-base
    build:
      script: python -m pip install .[hub] --no-deps --ignore-installed -vv
      noarch: python
    requirements:
      host:
        - __unix
        - python {{ python_min }}
        - pip
        - setuptools
      run:
        - {{ pin_subpackage(name + "-base", exact=True) }}
        - jupyterhub-base >=4.0.0
    test:
      requires:
        - python {{ python_min }}
      files:
        - tests/test_packaging.py
      imports:
        - cylc.flow
        - cylc.uiserver
      commands:
        - cylc version --long
        - cylc gui --help
        - cylc hubapp --help
        - command -v jupyter-cylc
        - command -v jupyter-cylchubapp
        - ./tests/test_packaging.py ui
        - ./tests/test_packaging.py py.typed

  # UIS with the full JupyterHub package
  # (recommended)
  - name: {{ name }}
    build:
      script: python -m pip install .[hub] --no-deps --ignore-installed -vv
      noarch: python
    requirements:
      host:
        - __unix
        - python {{ python_min }}
        - pip
        - setuptools
      run:
        - {{ pin_subpackage(name + "-base", exact=True) }}
        - jupyterhub >=4.0.0
    test:
      requires:
        - python {{ python_min }}
      files:
        - tests/test_packaging.py
      imports:
        - cylc.flow
        - cylc.uiserver
      commands:
        - cylc version --long
        - cylc gui --help
        - cylc hubapp --help
        - configurable-http-proxy --help
        - command -v jupyter-cylc
        - command -v jupyter-cylchubapp
        - ./tests/test_packaging.py ui
        - ./tests/test_packaging.py py.typed

about:
  home: https://github.com/cylc/cylc-uiserver
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: Cylc UI Server
  description: |
    This project contains the Cylc UI Server.

    A JupyterHub-compatible application, used to display
    the Cylc UI (or simply UI) to users, and to communicate
    with Workflow Services (WFS).
  doc_url: https://github.com/cylc/cylc-uiserver
  dev_url: https://github.com/cylc/cylc-uiserver

extra:
  recipe-maintainers:
    - hjoliver
    - oliver-sanders
    - MetRonnie
    - wxtim
