{% set name = "cylc-uiserver" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 796af6b1fb74b63cd87c1be304e56f7cc618d5264fc0b8dd974050271f673be8

build:
  number: 0
  # cylc-uiserver provides JupyterHub extensions and a small Jupyter Application. As JupyterHub
  # does not run on Windows, we skip the build for that platform here
  skip: true  # [py<37 or not linux]
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    # TODO: build failed with pytest-runner only, because the setup.py of cylc-uiserver specifies this
    # version of pytest-runner. Need to make pytest-runner a dependency only for python setup.py test
    # and then remove this from requirements|host in the recipe
    - pytest-runner ==4.4
  run:
    - python
    - cylc-flow ==8.0a2
    - graphene-tornado >=2.6
    - jupyterhub >=1.1
    - tornado >=6.0

test:
  imports:
    - cylc.uiserver
  commands:
    - cylc-uiserver --help

about:
  home: hhttps://github.com/cylc/cylc-uiserver
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: Cylc UI Server

  description: |
    This project contains the Cylc UI Server.
    A JupyterHub-compatible application, used to display
    the Cylc UI (or simply UI) to users, and to communicate
    with Workflow Services (WFS).
  doc_url: https://github.com/cylc/cylc-uiserver
  dev_url: https://github.com/cylc/cylc-uiserver

extra:
  recipe-maintainers:
    - hjoliver
    - kinow
    - oliver-sanders
